from .vidconv_recognizer import VidConvRecognizer
from .tsp_recognizer import TSPRecognizer
from .no_forgetting_recognizer import NoFogettingRecognizer
from .vidconv_multiview_recognizer import VidConvMultiViewRecognizer
